apiVersion: v1
kind: BuildConfig
metadata:
  name: frontend-pipeline
  labels:
    name: frontend-pipeline
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "frontend", "namespace": "fruits-catalog-dev", "kind": "DeploymentConfig"}, {"name": "frontendn", "namespace": "fruits-catalog-prod", "kind": "DeploymentConfig"}]'
spec:
  triggers:
    - type: GitHub
      github:
        secret: secret101
    - type: Generic
      generic:
        secret: secret101
  runPolicy: Serial
  source:
    type: None
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node ('nodejs') {
          stage ('Build') {
            openshiftBuild(namespace: 'fruits-catalog-dev', bldCfg: 'frontend', showBuildLogs: 'true')
          }
          stage ('Deploy Dev') {
            openshiftDeploy(namespace: 'fruits-catalog-dev', depCfg:  'frontend')
          }
          stage ('Acceptance Tests') {
            sleep 13
          }
          stage ('Promote to Prod') {
            openshiftTag(namespace: 'fruits-catalog-dev', sourceStream:'frontend', sourceTag:'latest', destinationStream:'frontend', destinationTag:'promoteToProd')
          }
          stage ('Deploy Prod') {
            openshiftDeploy(namespace: 'fruits-catalog-prod', depCfg:  'frontend')
          }
        }
  output:
  resources:
  postCommit: